"""added 3 databases

Revision ID: 03f3801c6252
Revises: 
Create Date: 2026-02-26 11:02:06.988563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f3801c6252'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status_enum') THEN
                CREATE TYPE lead_status_enum AS ENUM ('NEW', 'IN_PROGRESS', 'CONVERTED', 'LOST');
            END IF;
        END
        $$;
    """)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'CONVERTED', 'LOST', name='lead_status_enum',create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_source', 'leads', ['source'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'CONVERTED', 'LOST', name='lead_status_enum',create_type=False), nullable=False),
    sa.Column('to_status', postgresql.ENUM('NEW', 'IN_PROGRESS', 'CONVERTED', 'LOST', name='lead_status_enum',create_type=False), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_lead_id', 'action_history', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_lead_id', table_name='action_history')
    op.drop_table('action_history')
    op.drop_table('outbox_messages')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_source', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
